---
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
---

title: APLICACIONES MÓVILES Y SERVICIOS TELEMÁTICOS
description: PROFESORA MG. ADRIANA COLLAGUAZO JARAMILLO

google_analytics: G-711FMTCF19